---
- name: Update and upgrade Ubuntu servers
  hosts: linux
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
